[build]
  command = "npm run build"
  publish = "frontend/build"

[dev]
  command = "npm start"
  publish = "frontend/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  # Enable caching for static assets
  "/static/*"
    Cache-Control = "public, max-age=31536000, immutable"
  
  # Enable caching for index.html
  "/index.html"
    Cache-Control = "public, max-age=0, must-revalidate"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    buildCommand = "npm run build"

[functions]
  # Define the path to your serverless functions
  directory = "backend/functions"

[dev]
  # Configure your development environment
  command = "npm run dev"

[[redirects]]
  # Redirect to HTTPS
  from = "/*"
  to = "https://your-website.com/:splat"
  status = 301

[[headers]]
  # Set the X-Frame-Options header to deny
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"

[[headers]]
  # Set the X-XSS-Protection header to 1; mode=block
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
